name: Create Release

on:
  workflow_dispatch:
  #push:
    # Sequence of patterns matched against refs/tags
    #tags:
      #- 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Read theme version
        id: theme
        shell: bash
        run: |
          VERSION="$(awk -F': *' 'tolower($1)=="version" {print $2; exit}' style.css | tr -d '\r')"
          if [ -z "$VERSION" ]; then
            echo "Version not found in style.css" >&2
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build
        run: echo "${{ github.sha }} ${{ steps.theme.outputs.version }}" > Release.txt

      - name: Build theme zip
        shell: bash
        run: |
          set -euo pipefail

          THEME_SLUG="dws-2025"
          mkdir -p "dist/${THEME_SLUG}"

          # exclude dist to avoid recursion
          rsync -a --delete \
            --exclude "dist" \
            ./ "dist/${THEME_SLUG}/"

          # create zip
          (
            cd dist
            zip -r "${THEME_SLUG}.zip" "${THEME_SLUG}"
          )

      - name: Set version in style.css
        id: ver
        shell: bash
        run: |
          set -euo pipefail

          THEME_SLUG="dws-2025"
          NEW_VERSION="1.0.${{ github.run_number }}"
          STYLE="dist/${THEME_SLUG}/style.css"

          if [ ! -f "$STYLE" ]; then
            echo "Missing $STYLE" >&2
            exit 1
          fi

          # Replace the first match
          #sed -i -E "s/^Version:[[:space:]]*.*/Version: ${NEW_VERSION}/" "$STYLE"
          sed -E -i "s/^([[:space:]]*\*?[[:space:]]*)Version:[[:space:]]*.*/\1Version: ${NEW_VERSION}/" "$STYLE"

          echo "version=${NEW_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        # if: github.ref_type == 'tag'
        with:
          name: "v1.0.${{ github.run_number }}"
          #name: "v${{ steps.theme.outputs.version }}"
          #tag_name: "v${{ steps.theme.outputs.version }}"
          tag_name: "v1.0.${{ github.run_number }}"
          make_latest: true
          files: dist/dws-2025.zip
          #generate_release_notes: true
          preserve_order: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Print receipt
        shell: bash
        run: |
          echo '${{ toJson(steps.release.outputs) }}'
